FPS = 60
WINDOW_GAME_WIDTH = 360
WINDOW_GAME_HEIGHT = 640

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 640

# CHART Border constantes
CHART_WIDTH = 460
CHART_HEIGHT = 320

CHARTS_START_X = WINDOW_GAME_WIDTH

CHART_ROW_ONE_Y = 0
CHART_ROW_TWO_Y = CHART_ROW_ONE_Y + CHART_HEIGHT + 1